{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-modules
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.9.8.1"

source:
  fn: modules_0.9.8.1.tar.gz
  url:
    - https://github.com/klmr/modules/archive/version-0.9.8.1.tar.gz

  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, shiny
requirements:
  build:
    - r-base =3.4.1
    - r-roxygen2 =6.0.1
    - posix               # [win]
    - {{native}}toolchain # [win]
      #    - gcc                 # [not win]

  run:
    - r-base >=3.0.2
    - r-roxygen2 >=6.0.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modules')" # [not win]
    - "\"%R%\" -e \"library('modules')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/kmlr/modules
  license: Apache 2.0 + file LICENSE
  summary: Create reusable code modules in R. An alternative package management system for R, similar to module systems in Python, Ruby or JavaScript.
  license_family: Apache

# The original CRAN metadata for this package was:

#   Package: modules
#   Title: Modules for R
#   Version: 0.9.8.1
#   Author: Konrad Rudolph <konrad.rudolph@gmail.com>
#   Maintainer: Konrad Rudolph <konrad.rudolph@gmail.com>
#   Description: Create reusable code modules in R. An alternative package
#       management system for R, similar to module systems in Python, Ruby or
#           JavaScript.
#   Depends:
#         R (>= 3.0.2)
#   Imports:
#         tools,
#             roxygen2 (>= 6.0.1)
#   License: Apache License (== 2.0) | file LICENSE
#   LazyData: true
#   Encoding: UTF-8
#   Suggests:
#         knitr,
#             rmarkdown,
#                 testthat,
#                     shiny
#   VignetteBuilder: knitr
